### ISSUE TITLE
Exact same as previous lab - Curriculum issues

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-students/prototypal-oo-js-object-oriented-object-methods-lab-seattle-web-career-012819#2]
This lab is the EXACT same as the previous lab. It serves absolutely no benefit to repeat it, except to show that no one from the curriculum team has actually tested out the labs we are being given.

**Comment by maxwellbenton** [comment]
Hi @ScottDenton,

Thank you for spotting this and providing feedback. We've reordered the content in this section, removed a duplicate lesson and added in a lesson that had not been added and believe this issue has been resolved.

Thank you for participating in testing this curriculum content and for helping to improve it for future students! 💙
